backend:
  name: github
  repo: w1lli4m666-droid/movie8
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: posts
    label: 文章
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime }
      - { label: 封面图片, name: cover, widget: image, required: false }
      - { label: 摘要, name: summary, widget: text, required: false }
      - { label: 类型, name: tags, widget: list, field: { label: 类型, name: tag, widget: string }, required: false }
      - { label: 电影名称, name: movie_title, widget: string, required: false }
      - { label: 导演, name: director, widget: string, required: false }
      - { label: 编剧, name: screenwriter, widget: string, required: false }
      - { label: 主演, name: cast, widget: string, required: false }
      - { label: 上映年份, name: release_year, widget: string, required: false, hint: "支持格式：2019、2019-08-30、2019.08.30" }
      - { label: 评分, name: rating, widget: number, value_type: float, min: 0, max: 10, required: false }
      - { label: 正文, name: body, widget: markdown }
